[JX Sentinel]
NotifyUser=jackson
Notifications=true
Verbose=false

WatchPath=/opt/jx
WatchPath=/home/jackson

Extension=.desktop
Extension=.conf
Extension=.service
Extension=.sh
Extension=.c
Extension=.h
